apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  ports:
  - port: {{ .Values.service.clusterIPPort }}
    targetPort: {{ .Values.image.containerPort }}
    nodePort: 31000
  selector:
    app: webapp
